// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj6RLCks1i2G-KbCi4mRv4qZjkqG3_6dg',
    appId: '1:723083104634:web:5c7d3de5b8573ec76546c3',
    messagingSenderId: '723083104634',
    projectId: 'smart-expense-tracker-app-2026',
    authDomain: 'smart-expense-tracker-app-2026.firebaseapp.com',
    storageBucket: 'smart-expense-tracker-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAro6n3fuVGTLVahFYzpEKFtN3T9Qb4ME4',
    appId: '1:723083104634:android:559151fb8320d9936546c3',
    messagingSenderId: '723083104634',
    projectId: 'smart-expense-tracker-app-2026',
    storageBucket: 'smart-expense-tracker-app-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWZb1j9YeXpNjYDneaeJ73sTR61PEM_S8',
    appId: '1:723083104634:ios:65249e604c5968976546c3',
    messagingSenderId: '723083104634',
    projectId: 'smart-expense-tracker-app-2026',
    storageBucket: 'smart-expense-tracker-app-2026.firebasestorage.app',
    iosClientId: '723083104634-c4scnlklrstcdf7ptq7nui1hq4g4rvgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartExpenseTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWZb1j9YeXpNjYDneaeJ73sTR61PEM_S8',
    appId: '1:723083104634:ios:65249e604c5968976546c3',
    messagingSenderId: '723083104634',
    projectId: 'smart-expense-tracker-app-2026',
    storageBucket: 'smart-expense-tracker-app-2026.firebasestorage.app',
    iosClientId: '723083104634-c4scnlklrstcdf7ptq7nui1hq4g4rvgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj6RLCks1i2G-KbCi4mRv4qZjkqG3_6dg',
    appId: '1:723083104634:web:79b11a18dc7a94676546c3',
    messagingSenderId: '723083104634',
    projectId: 'smart-expense-tracker-app-2026',
    authDomain: 'smart-expense-tracker-app-2026.firebaseapp.com',
    storageBucket: 'smart-expense-tracker-app-2026.firebasestorage.app',
  );
}
